export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const FETCH_VIDEO_INFO = 'FETCH_VIDEO_INFO';
export const GET_SEARCH_TERM = 'GET_SEARCH_TERM';
export const CLEAN_UP_DATA = 'CLEAN_UP_DATA';

// TRENDS OPTIONS //

export const FETCH_TRENDS_VIDEO_INFO_FROM_CATEGORY =
  'FETCH_TRENDS_VIDEO_INFO_FROM_CATEGORY';

// SEARCH SUB MENU //

export const ACTIVE_SEARCH_SUB_MENU = 'ACTIVE_SEARCH_SUB_MENU';
export const ACTIVE_SEARCH_SUB_MENU_ITEM = 'ACTIVE_SEARCH_SUB_MENU_ITEM';
